##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [2]:
a = np.array([1, 2, 3, 4])
print(a*5)

[ 5 10 15 20]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [3]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([10,20,30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [4]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[10,20,30],[40,50,60]])

print(A + B)

[[11 22 33]
 [44 55 66]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [5]:
a = np.array([10, 20, 30, 40])
print(np.sum(a))
print(np.mean(a))
print(np.var(a))
print(np.std(a))
print(np.max(a),np.min(a))

100
25.0
125.0
11.180339887498949
40 10


You can also do the axis based operations row-Wise and Colum-wise

In [6]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.sum(data))
print(np.max(data))
print(np.min(data))
print(np.var(data))
print(np.std(data))
print(np.mean(data))
print(np.sum(data,axis=1))
print(np.max(data,axis=1))
print(np.min(data,axis=1))
print(np.var(data,axis=1))
print(np.std(data,axis=1))
print(np.mean(data,axis=1))
print(np.sum(data,axis=0))
print(np.max(data,axis=0))
print(np.min(data,axis=0))
print(np.var(data,axis=0))
print(np.std(data,axis=0))
print(np.mean(data,axis=0))

45
9
1
6.666666666666667
2.581988897471611
5.0
[ 6 15 24]
[3 6 9]
[1 4 7]
[0.66666667 0.66666667 0.66666667]
[0.81649658 0.81649658 0.81649658]
[2. 5. 8.]
[12 15 18]
[7 8 9]
[1 2 3]
[6. 6. 6.]
[2.44948974 2.44948974 2.44948974]
[4. 5. 6.]
