##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [1]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 3)
2
9
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[3])

4


Now lets see the 2D indexing aswell

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[2])

[7 8 9]


In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[2,2])

9


Now we can also do the slicing lets see the **slicing in 1D**

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:7])
print(arr[::-1])
print(arr[::2])

[3 4 5 6 7]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]


1D slicing was really easy now lets see the **slicing in 2D**

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,0:2])
print(arr[0::,0::])
print(arr[::-1,::-1])

[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


There is one more thing known as **Boolean indexing**

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr>5])


[6 7 8 9]


In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[arr>5]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([6, 7, 8, 9])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [24]:
arr=np.arange(1,10)
arr.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
