##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print("Original:", arr)

print("Fancy indexing:", arr[[0, 2, 4]])

Original: [10 20 30 40 50 60]
Fancy indexing: [10 30 50]


You can do this fancy indexing in 2D Matrix aswell

In [2]:
matrix = np.arange(1, 13).reshape(3, 4)
print("Matrix:\n", matrix)
print("Select [row0,col1], [row1,col2]:", matrix[[0,1],[1,2]])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Select [row0,col1], [row1,col2]: [2 7]


##Conditional Selection
Find values based on conditions or replace them.

In [4]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix[matrix>4])
print(np.where(matrix > 4))
print(np.where(matrix>4,matrix,0))


[ 5  6  7  8  9 10 11 12]
(array([1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3]))
[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [7]:
arr = np.array([42, 5, 18, 23])
np.sort(arr)

array([ 5, 18, 23, 42])

In [6]:
arr = np.array([42, 5, 18, 23])
idx=np.argsort(arr)
print(idx)
print(arr[idx])

[1 2 3 0]
[ 5 18 23 42]


In [8]:
mat = np.array([[3,7,1],[9,4,6]])
print(np.sort(mat, axis=1))
print(np.sort(mat, axis=0))

[[1 3 7]
 [4 6 9]]
[[3 4 1]
 [9 7 6]]


##Concatenation & Stacking

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


Vertical & Horizontal Stacking

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack([a,b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.hstack([a,b]))

[[1 2 5 6]
 [3 4 7 8]]
